---
title: "Computational Musicology - Final Portfolio"
author: "Roan van Blanken"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    self_contained: false
---

```{r setup, include=FALSE}
library(flexdashboard)
library(spotifyr)
library(purrr)
library(dplyr)
library(ggplot2)
library(plotly)
library(tidyverse)
library(compmus)
```

Corpus
=====================================

Column {data-width=500}
-----------------------------------------------------------------------

### Chart A

```{r}

```
**OLD VERSION**

My corpus for my final portfolio is a playlist of songs that I have labeled as "Numbers I Like." This playlist contains a diverse range of songs, making it difficult to categorize into a specific genre. The majority of the songs in my playlist fall under the categories of pop, 70s, 80s, 90s musical, and some rock, but there are also elements of other genres present.

I chose this playlist as my corpus because it is a collection of songs that hold personal meaning to me. Most of the songs have a specific memory or emotion attached to it, making it a unique and representative representation of my musical taste. 

One of the interesting aspects of my corpus is the lack of cohesiveness in terms of genre. This allows for a wide range of comparisons to be made, as well as a glimpse into my own  taste. The tracks in my corpus can be compared in terms of popularity, musical style, and cultural significance. I expect that the most popular songs in my playlist will have a different musical style than the less popular ones, and that the songs with cultural significance will be unique in comparison to the others.
The tracks in my corpus are representative of my personal musical taste, but may not accurately represent the wider musical landscape. The playlist was created through my personal listening habits and does not take into account other sources of music I listen to outside of Spotify.

There are several tracks in my corpus that are either extremely typical or atypical. For example, the song "Bohemian Rhapsody" by Queen is an atypical track in my playlist due to its cultural significance and popularity, compared to other songs in the playlist. On the other hand, a typical track in my playlist may be a pop song that is popular but holds less cultural significance.

In conclusion, my "Numbers I Like" playlist is a unique corpus that represents my personal musical taste, showcasing a diverse range of songs that hold personal meaning. Its nature provides a range of opportunities for comparisons and analyses, allowing for an interesting and reflective final portfolio.

Column {data-width=250}
-----------------------------------------------------------------------

### Chart B

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/6pl0C7qbIl5uoY3Tdf82oa?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

Column {data-width=250}
-----------------------------------------------------------------------

### Chart C

<iframe style="border-radius:12px" src="https://open.spotify.com/embed/playlist/4bJQX5w7W4wEnHLmWqUIVY?utm_source=generator" width="100%" height="352" frameBorder="0" allowfullscreen="" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture" loading="lazy"></iframe>

Homework - week 7
=====================================

Column {data-width=500}
-----------------------------------------------------------------------
### Plot 1

```{r}
my_faves <- get_playlist_audio_features("", "6pl0C7qbIl5uoY3Tdf82oa")

# Start with modes
my_faves <- my_faves %>%
  mutate(mode = ifelse(mode == 0, "Minor", "Major"))

# Create the scatterplot
my_faves %>%
  ggplot(aes(x = valence, y = energy, size = loudness, color = mode)) +
  geom_point() +
  geom_rug(linewidth = 0.1) +
  scale_x_continuous(limits = c(0, 1), breaks = c(0, 0.50, 1), minor_breaks = NULL) +
  scale_y_continuous(limits = c(0, 1), breaks = c(0, 0.50, 1), minor_breaks = NULL) +
  scale_color_brewer(type = "qual", palette = "Paired", name = "Mode") +
  scale_size_continuous(trans = "exp", guide = "none") +
  theme_light() +
  labs(x = "Valence", y = "Energy",
       title = "My Favorite Tracks",
       subtitle = "Plotting valence, energy, and loudness",
       caption = "Data source: Spotify API\nAuthor: Roan van Blanken")
```

Column {data-width=500}
-----------------------------------------------------------------------
### Plot 2

```{r}

# Get playlists
my_faves <- get_playlist_audio_features("", "6pl0C7qbIl5uoY3Tdf82oa")
soft_10s <- get_playlist_audio_features("", "37i9dQZF1DX1uHCeFHcn8X")

# Create the density plot
ggplot() +
  geom_density(aes(x = valence, color = "My Favorites"), data = my_faves, fill = "red", alpha = 0.5) +
  geom_density(aes(x = valence, color = "Soft 10s"), data = soft_10s, fill = "purple", alpha = 0.5) +
  scale_color_manual(values = c("My Favorites" = "red", "Soft 10s" = "purple")) +
  theme_light() +
  labs(x = "Valence", y = "Density",
       title = "Valence Distribution of My Favorite Tracks and Soft 10s",
       subtitle = "Based on Spotify audio features",
       caption = "Data source: Spotify API\nAuthor: Roan van Blanken") +
  guides(color = guide_legend(override.aes = list(fill = c("red", "orchid")))) 
```

Corpus Idea
=====================================

Column {data-width=500}
-----------------------------------------------------------------------
### Plot 1

```{r}

# Get playlists
songs_i_like <- get_playlist_audio_features("", "6pl0C7qbIl5uoY3Tdf82oa")
songs_i_dislike <- get_playlist_audio_features("", "4bJQX5w7W4wEnHLmWqUIVY")

# Create the density plot
plot1 <- ggplot() +
  geom_density(aes(x = speechiness, color = "Songs I like"), data = songs_i_like, fill = "lightblue", alpha = 0.5) +
  geom_density(aes(x = speechiness, color = "Songs I dislike"), data = songs_i_dislike, fill = "lightpink", alpha = 0.5) +
  scale_color_manual(values = c("Songs I like" = "lightblue", "Songs I dislike" = "lightpink")) +
  theme_light() +
  labs(x = "Speechiness", y = "Density",
       title = "Speechiness Distribution of My Favorite Tracks and Songs I dislike",
       subtitle = "Based on Spotify audio features",
       caption = "Data source: Spotify API\nAuthor: Roan van Blanken") +
  guides(color = guide_legend(override.aes = list(fill = c("lightpink", "lightblue"))))

plotly_object1 <- ggplotly(plot1)

plot1
```

Column {data-width=500}
-----------------------------------------------------------------------
### Plot 2

```{r}

# Create the scatter plot
plot2 <- ggplot() +
  geom_point(aes(x = instrumentalness, y = energy, color = "Songs I like"), data = songs_i_like, alpha = 0.5) +
  geom_point(aes(x = instrumentalness, y = energy, color = "Songs I dislike"), data = songs_i_dislike, alpha = 0.5) +
  scale_color_manual(values = c("Songs I like" = "green", "Songs I dislike" = "orange")) +
  theme_light() +
  labs(x = "Instrumentalness", y = "Energy",
       title = "Instrumentalness and Energy of My Favorite Tracks and Songs I dislike",
       subtitle = "Based on Spotify audio features",
       caption = "Data source: Spotify API\nAuthor: Roan van Blanken")

plotly_object2 <- ggplotly(plot2)

plot2

```
